= jvpp-benchmark

Provides JMH based benchmarks JVpp (Java API for VPP).

== AclUpdateBenchmark

Creates ACL of size aclSize using acl_add_replace,
then assigns it to loopback interface using acl_interface_set_acl_list.

Then ACL is updated synchronously using acl_add_replace.
By default 20x2s warmup and 100x2s measurment iterations
are performed.

VPP is restarted after each iteration.

Each invocation of acl_add_replace uses ACL from precomputed
set of ACLs of size aclSetSize.
ACLs from the set are used in round-robin fashion.

Compile:
[source,shell]
---
cd $HC2VPP_ROOT/it/jvpp-benchmark
mvn clean install
---

Run with:
[source,shell]
---
sudo java -jar ./target/jvpp-benchmark-exec.jar
---

To specify aclSize (default=100), use:
[source,shell]
---
sudo java -jar ./target/jvpp-benchmark-exec.jar -p aclSize=1000
---

To specify aclSetSize (default=100), use:
[source,shell]
---
sudo java -jar ./target/jvpp-benchmark-exec.jar -p aclSetSize=1000
---

To test interface in bridged (L2) / routed (L3) mode (default=L3), use:
[source,shell]
---
sudo java -jar ./target/jvpp-benchmark-exec.jar -p mode=L2
---

To see more options, use
[source,shell]
---
java -jar ./target/jvpp-benchmark-exec.jar -h
---
