== User guide

=== Running Honeycomb
link:user_running_honeycomb.html[Running Honeycomb]

=== Troubleshooting
link:user_troubleshooting.html[Troubleshooting]

=== Honeycomb and ODL
link:user_honeycomb_and_ODL.html[Mounting Honeycomb in ODL]

=== Configuration files
Honeycomb's configuration files present within its distribution:

* Honeycomb infra:
** {project-infra-git-web}/infra/minimal-distribution/src/main/resources/honeycomb-minimal-resources/config/honeycomb.json?h={project-branch}[Honeycomb base configuration]
* Honeycomb vpp plugins commons:
** {project-git-web}/vpp-common/vpp-common-integration/src/main/resources/honeycomb-minimal-resources/config/jvpp.json?h={project-branch}[VPP plugins common configuration]
* LISP plugin:
** {project-git-web}/lisp/lisp2vpp/src/main/resources/honeycomb-minimal-resources/config/lisp.json?h={project-branch}[LISP plugin for Honeycomb configuration]
* Routing plugin:
** {project-git-web}/routing/routing-impl/src/main/resources/honeycomb-minimal-resources/config/routing.json?h={project-branch}[Routing plugin for Honeycomb configuration]
* VPP management plugin:
** {project-git-web}/vpp-management/impl/src/main/resources/honeycomb-minimal-resources/config/vpp-management.json?h={project-branch}[VPP management plugin configuration]

=== YANG models

* V3PO plugin
** {project-git-web}/v3po/api/src/main/yang?h={project-branch}[V3PO YANG models]
* LISP plugin
** {project-git-web}/lisp/api/src/main/yang?h={project-branch}[LISP YANG models]
* NSH plugin
** {project-git-web}/nsh/api/src/main/yang?h={project-branch}[NSH YANG models]
* NAT plugin
** {project-git-web}/nat/nat-api/src/main/yang?h={project-branch}[NAT YANG models]
* iOAM plugin
** {project-git-web}/ioam/api/src/main/yang?h={project-branch}[IOAM YANG models]
* Interface role plugin
** {project-git-web}/interface-role/api/src/main/yang?h={project-branch}[Interface role YANG models]
* Routing plugin
** {project-git-web}/routing/routing-api/src/main/yang?h={project-branch}[Routing YANG models]
* ACL plugin
** {project-git-web}/acl/acl-api/src/main/yang?h={project-branch}[ACL YANG models]
* Context models
** {project-git-web}/vpp-common/naming-context-api/src/main/yang?h={project-branch}[Context YANG models]
* VPP management plugin
** {project-git-web}/vpp-management/api/src/main/yang?h={project-branch}[VPP management YANG models]
* L3 plugin
** {project-git-web}/l3/api/src/main/yang?h={project-branch}[L3 YANG models]
* DHCP plugin
** {project-git-web}/dhcp/dhcp-api/src/main/yang?h={project-branch}[DHCP YANG models]
* VPP classifier plugin
** {project-git-web}/vpp-classifier/api/src/main/yang?h={project-branch}[VPP classifier YANG models]

=== POSTMAN collections

* V3PO plugin
** {project-git-web}/v3po/postman_rest_collection.json?h={project-branch}[V3PO postman collection]
* LISP plugin
** {project-git-web}/lisp/lisp_postman_collection.json?h={project-branch}[LISP postman collection]
** {project-git-web}/lisp/gpe_postman_collection.json?h={project-branch}[LISP GPE postman collection]
* NSH plugin
** {project-git-web}/nsh/nsh_postman_collection.json?h={project-branch}[NSH postman collection]
* NAT plugin
** {project-git-web}/nat/postman_rest_collection.json?h={project-branch}[NAT postman collection]
* iOAM plugin
** {project-git-web}/ioam/ioam_postman_collection.json?h={project-branch}[IOAM postman collection]
* Interface role plugin
** {project-git-web}/interface-role/interface_role_postman_collection.json?h={project-branch}[Interface role postman collection]
* Routing plugin
** {project-git-web}/routing/routing_postman_collection.json?h={project-branch}[Routing postman collection]
** {project-git-web}/routing/routing_adv_postman_collection.json?h={project-branch}[Routing advertisements postman collection]
* ACL plugin
** {project-git-web}/acl/acl_postman_collection.json?h={project-branch}[ACL postman collection]
* VPP management plugin
** {project-git-web}/vpp-management/vpp_management_postman_collection.json?h={project-branch}[VPP management postman collection]
* L3 plugin
** {project-git-web}/l3/impl/l3_postman_collection.json?h={project-branch}[L3 postman collection]
* DHCP plugin
** {project-git-web}/dhcp/dhcp_postman_collection.json?h={project-branch}[DHCP postman collection]
* VPP classifier plugin
** {project-git-web}/vpp-classifier/vpp_classifier_postman_collection.json?h={project-branch}[VPP classifier postman collection]
** {project-git-web}/vpp-classifier/policer_postman_collection.json?h={project-branch}[Policer postman collection]
* BGP plugin
** {project-git-web}/bgp/bgp_postman_collection.json?h={project-branch}[BGP postman collection].
