#!/bin/bash
# release version
echo RELEASE
#
# snapshot version
#
# Increasing the build number by a certain margin.
# Necessary due to honeycomb - hc2vpp split. Build_number counter was reset
# rewriting older packages
# echo $(expr $BUILD_NUMBER + 2000)