#!/bin/bash
#
# Snapshot version (do not use on stable branch)
#
#
echo $(expr $BUILD_NUMBER)
#
# Stable versions
#
# echo RC1~$BUILD_NUMBER
# echo RC1
# echo RC2~$BUILD_NUMBER
# echo RC2
#
# Release snapshot (1.19.08~XXX, 1.19.08.1~XXX, ...)
# echo RELEASE~$BUILD_NUMBER
#
# Release version (1.19.08, 1.19.08.1, ...)
# echo RELEASE