#!/bin/bash
# defines vpp and vpp-plugins dependencies for rpm packages
# using range
echo "vpp >= 17.10, vpp < 17.11, vpp-plugins >= 17.10, vpp-plugins < 17.11"
# or specific vpp version
#echo "vpp = 17.10-rc2, vpp-plugins = 17.10-rc2"
