#!/bin/bash
# defines vpp and vpp-plugins dependencies for debian packages
# using range
echo "vpp (>= 18.04), vpp (<< 18.05), vpp-plugins (>= 18.04), vpp-plugins (<< 18.05)"
# or specific vpp version
#echo "vpp (= 18.04-rc1), vpp-plugins (= 18.04-rc1)"
