#!/bin/bash
# defines vpp and vpp-plugins dependencies for debian packages
# using range
echo "vpp (>= 18.07), vpp (<< 18.08), vpp-plugins (>= 18.07), vpp-plugins (<< 18.08)"
# or specific vpp version
#echo "vpp (= 18.07-rc1), vpp-plugins (= 18.07-rc1)"
